### ISSUE TITLE
An unhandled exception occurred: The target entry-point "single-spa-angular" has missing dependencies:

### ISSUE THREAD

**Issue by shanmukha6** [single-spa/single-spa-playground#45]
An error occurred during the build:
Error: The target entry-point "single-spa-angular" has missing dependencies:
 - single-spa

    at TargetedEntryPointFinder.findEntryPoints (C:\Users\skondapalakala\MicroFrontends\Single-SPA-demo\my-app\node_modules\@angular\compiler-cli\ngcc\src\entry_point_finder\targeted_entry_point_finder.js:40:23)
    at C:\Users\skondapalakala\MicroFrontends\Single-SPA-demo\my-app\node_modules\@angular\compiler-cli\ngcc\src\execution\analyze_entry_points.js:29:41
    at SingleProcessExecutorSync.SingleProcessorExecutorBase.doExecute (C:\Users\skondapalakala\MicroFrontends\Single-SPA-demo\my-app\node_modules\@angular\compiler-cli\ngcc\src\execution\single_process_executor.js:28:29)
    at C:\Users\skondapalakala\MicroFrontends\Single-SPA-demo\my-app\node_modules\@angular\compiler-cli\ngcc\src\execution\single_process_executor.js:57:59
    at SyncLocker.lock (C:\Users\skondapalakala\MicroFrontends\Single-SPA-demo\my-app\node_modules\@angular\compiler-cli\ngcc\src\locking\sync_locker.js:34:24)
    at SingleProcessExecutorSync.execute (C:\Users\skondapalakala\MicroFrontends\Single-SPA-demo\my-app\node_modules\@angular\compiler-cli\ngcc\src\execution\single_process_executor.js:57:27)
    at Object.mainNgcc (C:\Users\skondapalakala\MicroFrontends\Single-SPA-demo\my-app\node_modules\@angular\compiler-cli\ngcc\src\main.js:74:25)
    at Object.process (C:\Users\skondapalakala\MicroFrontends\Single-SPA-demo\my-app\node_modules\@angular\compiler-cli\ngcc\index.js:29:23)
    at NgccProcessor.processModule (C:\Users\skondapalakala\MicroFrontends\Single-SPA-demo\my-app\node_modules\@ngtools\webpack\src\ngcc_processor.js:163:16)
    at C:\Users\skondapalakala\MicroFrontends\Single-SPA-demo\my-app\node_modules\@ngtools\webpack\src\ivy\host.js:109:18
    at Array.map (<anonymous>)
    at Object.host.resolveModuleNames (C:\Users\skondapalakala\MicroFrontends\Single-SPA-demo\my-app\node_modules\@ngtools\webpack\src\ivy\host.js:37:32)
    at actualResolveModuleNamesWorker (C:\Users\skondapalakala\MicroFrontends\Single-SPA-demo\my-app\node_modules\typescript\lib\typescript.js:105298:133)
    at resolveModuleNamesWorker (C:\Users\skondapalakala\MicroFrontends\Single-SPA-demo\my-app\node_modules\typescript\lib\typescript.js:105536:26)
    at resolveModuleNamesReusingOldState (C:\Users\skondapalakala\MicroFrontends\Single-SPA-demo\my-app\node_modules\typescript\lib\typescript.js:105650:24)
An unhandled exception occurred: The target entry-point "single-spa-angular" has missing dependencies:
 - single-spa

See "C:\Users\SKONDA~1\AppData\Local\Temp\ng-TV2w6O\angular-errors.log" for further details.
PS C:\Users\skondapalakala\MicroFrontends\Single-SPA-demo\my-app> npm run serve:single-spa:my-app

> my-app@0.0.0 serve:single-spa:my-app C:\Users\skondapalakala\MicroFrontends\Single-SPA-demo\my-app
> ng s --project my-app --disable-host-check --port 4200 --deploy-url http://localhost:4200/ --live-reload false

Option "deployUrl" is deprecated: Use the "deployUrl" option in the browser builder instead.
? Port 4200 is already in use.
Would you like to use a different port? Yes
    Warning: --deploy-url and/or --base-href contain unsupported values for ng serve. Default serve path of '/' used. Use --serve-path to override.
Warning: Running a server with --disable-host-check is a security risk. See https://medium.com/webpack/webpack-dev-server-middleware-security-issues-1489d950874a for more information.
An unhandled exception occurred: The target entry-point "single-spa-angular" has missing dependencies:
 - single-spa

See "C:\Users\SKONDA~1\AppData\Local\Temp\ng-YCVY4f\angular-errors.log" for further details.
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! errno ENOENT
npm ERR! my-app@0.0.0 serve:single-spa:my-app: `ng s --project my-app --disable-host-check --port 4200 --deploy-url http://localhost:4200/ --live-reload false`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the my-app@0.0.0 serve:single-spa:my-app script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\skondapalakala\AppData\Roaming\npm-cache\_logs\2021-04-27T14_53_31_259Z-debug.log
PS C:\Users\skondapalakala\MicroFrontends\Single-SPA-demo\my-app> An unhandled exception occurred: The target entry-point "single-spa-angular" has missing dependencies:
An : The term 'An' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and 
try again.
At line:1 char:1
+ An unhandled exception occurred: The target entry-point "single-spa-a ...

**Comment by joeldenning** [comment]
Hmm this shouldn't happen because single-spa is in the import map: https://github.com/single-spa/single-spa-playground/blob/a72bc26a7e67c517d2a059d1b117c546a139008d/index.html#L16

Not sure what would cause this.
