### ISSUE TITLE
zone.min.js:13 Uncaught Error: application '@single-spa/welcome' died in status LOADING_SOURCE_CODE: Unable to resolve bare specifier '@single-spa/welcome' from http://localhost:9001/ (SystemJS Error#8 https://git.io/JvFET#8)     at throwUnresolved (system.js:698:11)     at systemJSPrototype.resolve (system.js:694:102)     at system.js:227:21     at e.invoke (zone.min.js:13:7171)     at t.run (zone.min.js:13:2271)     at zone.min.js:27:2767     at e.invokeTask (zone.min.js:13:7855)     at t.runTask (zone.min.js:13:2934)     at _ (zone.min.js:13:10171)

### ISSUE THREAD

**Issue by karrivinodh** [single-spa/single-spa-playground#69]

**Comment by joeldenning** [comment]
Not enough information to diagnose the error. single-spa/welcome is in the import map for root configs generated by create-single-spa, but I confirmed that a newly generated root config successfully loads the single-spa/welcome microfrontend
